export type Language = 'en' | 'cs';
export const LANGUAGE_KEY = 'toxiq-language';
export const messages = {
  profiles: ['Profiles', 'Profily'], key: ['Key', 'Klávesa'],
  key_type: ['Keyboard key', 'Klávesa'], hotkey_type: ['Shortcut', 'Zkratka'], text_type: ['Type text', 'Napsat text'], media_type: ['Media control', 'Ovládání médií'], mouse_type: ['Mouse action', 'Akce myši'],
  select_key: ['Select a key to edit', 'Vyber klávesu k úpravě'], key_grid: ['TOXIQ keys, three by two', 'Klávesy TOXIQ, tři krát dvě'],
  label: ['Key label', 'Název klávesy'], action: ['Action', 'Akce'], message: ['Text to type', 'Text k napsání'],
  text_placeholder: ['Type your message…', 'Napiš svoji zprávu…'], shortcut: ['Shortcut', 'Zkratka'], record: ['Record shortcut', 'Zaznamenat zkratku'],
  press_shortcut: ['Press your shortcut…', 'Stiskni zkratku…'], cancel: ['Cancel', 'Zrušit'],
  typing_layout: ['Typing layout', 'Rozložení pro psaní'], layout_hint: ['Match the keyboard layout in Windows.', 'Zvol stejné rozložení jako ve Windows.'],
  US: ['English · US', 'Anglické · US'], CZ: ['Czech · QWERTZ', 'České · QWERTZ'], CZ_QWERTY: ['Czech · QWERTY', 'České · QWERTY'],
  connect: ['Connect device', 'Připojit zařízení'], connect_demo: ['Connect demo', 'Připojit demo'], connecting: ['Connecting…', 'Připojuji…'], connected: ['Connected', 'Připojeno'], disconnected: ['Not connected', 'Nepřipojeno'], disconnect: ['Disconnect', 'Odpojit'],
  save: ['Save to device', 'Uložit do zařízení'], save_demo: ['Save to demo', 'Uložit do dema'], saving: ['Saving…', 'Ukládám…'], reading: ['Reading…', 'Načítám…'], read: ['Load from device', 'Načíst ze zařízení'],
  saved: ['Saved and verified', 'Uloženo a ověřeno'], saved_demo: ['Saved to demo', 'Uloženo do dema'], changes: ['Unsaved device changes', 'Změny čekají na zápis'], current: ['Device is up to date', 'Zařízení je aktuální'], demo_current: ['Demo is up to date', 'Demo je aktuální'], connect_hint: ['Connect your TOXIQ to save.', 'Pro uložení připoj TOXIQ.'], demo_hint: ['Browser demo · no hardware connection', 'Webové demo · bez spojení s hardwarem'],
  draft_saved: ['Draft saved', 'Rozpracované změny uloženy'], storage_paused: ['Draft autosave paused', 'Automatické ukládání pozastaveno'], storage_failed: ['Local storage unavailable. Export your profiles.', 'Lokální úložiště není dostupné. Exportuj profily.'],
  more: ['More options', 'Další možnosti'], import: ['Import profiles', 'Importovat profily'], export: ['Export profiles', 'Exportovat profily'], language: ['Language', 'Jazyk'], theme: ['Switch appearance', 'Přepnout vzhled'], close: ['Dismiss notification', 'Zavřít oznámení'], skip: ['Skip to keys', 'Přejít na klávesy'], brightness: ['Backlight', 'Podsvícení'], physical_keys: ['physical keys', 'fyzické klávesy'], future_key: ['Saved slot · not fitted on V0', 'Uložená pozice · V0 ji nemá zapojenou'],
  connected_notice: ['Connected. Load your device settings or save this draft.', 'Připojeno. Načti nastavení zařízení, nebo ulož rozpracované změny.'], read_notice: ['Loaded from device.', 'Načteno ze zařízení.'], new_changes: ['Saved. Your latest edits still need saving.', 'Uloženo. Nejnovější úpravy ještě čekají na zápis.'], imported: ['Profiles imported.', 'Profily importovány.'], exported: ['Profiles exported.', 'Profily exportovány.'], migrated: ['Your existing profiles were kept.', 'Tvoje dosavadní profily zůstaly zachované.'],
  local_corrupt: ['Your saved draft could not be read. Original data was kept. Export before closing.', 'Uložené nastavení nešlo načíst. Původní data zůstala zachovaná. Před zavřením použij export.'], edited_during_read: ['You edited the draft while reading. Your changes were kept; load the device again.', 'Během načítání jsi upravil nastavení. Změny zůstaly zachované; načti zařízení znovu.'], backup_failed: ['Could not back up your draft. Export it before loading the device.', 'Rozpracované nastavení nelze zálohovat. Před načtením ho exportuj.'],
  no_device: ['Connect your XIAO with a USB data cable and install TOXIQ firmware 0.5.', 'Připoj XIAO datovým USB kabelem a nahraj TOXIQ firmware 0.5.'], file_large: ['File too large. Maximum size is 64 kB.', 'Soubor je příliš velký. Maximum je 64 kB.'], json_invalid: ['This file does not contain valid JSON.', 'Soubor neobsahuje platný JSON.'],
  label_required: ['Enter a key label.', 'Doplň název klávesy.'], label_long: ['Key labels can have up to 12 characters.', 'Název klávesy může mít nejvýš 12 znaků.'], text_required: ['Enter the text to type.', 'Doplň text k napsání.'], text_long: ['Text can have up to 240 characters.', 'Text může mít nejvýš 240 znaků.'], text_characters: ['This text contains characters unavailable in the selected typing layout.', 'Text obsahuje znaky nedostupné ve zvoleném rozložení.'], key_invalid: ['Select a valid key.', 'Vyber platnou klávesu.'], hotkey_invalid: ['Use a shortcut such as CTRL+SHIFT+M.', 'Použij zkratku jako CTRL+SHIFT+M.'], media_invalid: ['Select a media action.', 'Vyber mediální akci.'], mouse_invalid: ['Select a mouse action.', 'Vyber akci myši.'],
  config_version: ['Unsupported TOXIQ profile format.', 'Nepodporovaný formát TOXIQ profilů.'], brightness_invalid: ['Brightness must be a whole number from 0 to 100.', 'Jas musí být celé číslo od 0 do 100.'], profile_invalid: ['Each profile must contain exactly six valid keys.', 'Každý profil musí obsahovat přesně šest platných kláves.'], active_invalid: ['Invalid active profile.', 'Neplatný aktivní profil.'], layout_invalid: ['Select a supported typing layout.', 'Vyber podporované rozložení pro psaní.'], config_large: ['Device settings exceed the 10 kB limit.', 'Nastavení zařízení přesahuje limit 10 kB.'], firmware_required: ['Update your device to TOXIQ firmware 0.5 before connecting.', 'Před připojením aktualizuj zařízení na TOXIQ firmware 0.5.'], storage_unavailable: ['Device storage is unavailable.', 'Paměť zařízení není dostupná.'],
  conflict: ['Device settings changed. Load them again before saving.', 'Nastavení zařízení se změnilo. Před uložením ho znovu načti.'], storage: ['Device storage write failed. Your draft was kept.', 'Zápis do paměti zařízení selhal. Rozpracované změny zůstaly zachované.'], invalid_config: ['The firmware rejected these settings. Check the actions and text.', 'Firmware odmítl nastavení. Zkontroluj akce a text.'], protocol: ['Incompatible USB protocol.', 'Nekompatibilní USB protokol.'], too_large: ['Device memory limit exceeded.', 'Překročen limit paměti zařízení.'],
  usb_disconnected: ['USB device disconnected.', 'USB zařízení se odpojilo.'], usb_failed: ['USB connection failed. Check the cable and close Serial Monitor.', 'USB spojení selhalo. Zkontroluj kabel a zavři Serial Monitor.'], usb_closed: ['USB connection closed.', 'USB spojení ukončeno.'], response_large: ['The device response is too large.', 'Odpověď zařízení je příliš velká.'], response_invalid: ['Invalid device response.', 'Neplatná odpověď zařízení.'], request_rejected: ['The device rejected the request.', 'Zařízení odmítlo požadavek.'], connect_first: ['Connect your device first.', 'Nejdřív připoj zařízení.'], device_busy: ['The device is busy.', 'Zařízení právě zpracovává požadavek.'], request_large: ['The request is too large.', 'Požadavek je příliš velký.'], timeout: ['The device timed out. Reconnect and load its settings before retrying.', 'Zařízení neodpovědělo včas. Připoj ho znovu a před opakováním načti jeho nastavení.'], send_failed: ['USB send failed.', 'Odeslání přes USB selhalo.'], revision_invalid: ['Invalid device revision.', 'Neplatná revize zařízení.'], session_unverified: ['The USB connection has not been verified.', 'USB spojení není ověřené.'], revision_unconfirmed: ['The device did not confirm the write revision.', 'Zařízení nepotvrdilo revizi zápisu.'], readback_failed: ['Write verification failed. Load the device and retry.', 'Kontrola zápisu selhala. Načti zařízení a zkus zápis znovu.'], unauthorized: ['Unauthorized request.', 'Nepovolený požadavek.'], operation_failed: ['Operation failed.', 'Operace selhala.'], demo_disconnected: ['The demo disconnected while saving. Retry.', 'Demo se během ukládání odpojilo. Zkus to znovu.'],
  PLAY_PAUSE: ['Play / pause', 'Přehrát / pozastavit'], VOLUME_MUTE: ['Mute', 'Ztlumit zvuk'], VOLUME_UP: ['Volume up', 'Zvýšit hlasitost'], VOLUME_DOWN: ['Volume down', 'Snížit hlasitost'], NEXT_TRACK: ['Next track', 'Další skladba'], PREVIOUS_TRACK: ['Previous track', 'Předchozí skladba'], LEFT_CLICK: ['Left click', 'Levé tlačítko'], RIGHT_CLICK: ['Right click', 'Pravé tlačítko'], MIDDLE_CLICK: ['Middle click', 'Prostřední tlačítko'], SCROLL_UP: ['Scroll up', 'Posunout nahoru'], SCROLL_DOWN: ['Scroll down', 'Posunout dolů'],
} as const;
export type MessageKey = keyof typeof messages;
export function translate(key: MessageKey, language: Language): string { return messages[key][language === 'cs' ? 1 : 0]; }
export function errorText(value: string, language: Language): string {
  if (Object.hasOwn(messages, value)) return translate(value as MessageKey, language);
  const match = value.match(/^(.+) \/ (\d+) \/ ([a-z_]+)$/);
  if (match) return `${match[1]} / ${translate('key', language)} ${match[2]}: ${errorText(match[3], language)}`;
  return value;
}
export function readLanguage(): Language { try { return localStorage.getItem(LANGUAGE_KEY) === 'cs' ? 'cs' : 'en'; } catch { return 'en'; } }
